spring:
  datasource:
    url: jdbc:sqlite:data.db
    driver-class-name: org.sqlite.JDBC
wss:
  port: 6034
  password: "123456"
# 必须配置
spt:
  redis:
    port: 6379
    host: "localhost"

m-language: "zh"